name: tv_kontrol_mobil
description: "Android TV Kontrol Uygulaması - MQTT ile Görsel Paylaşımı"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_storage: ^12.4.10
  
  # QR Scanner - CLEAN VERSION
  mobile_scanner: ^5.2.3
  
  # Permissions
  permission_handler: ^11.3.1
  
  # UUID
  uuid: ^4.5.1
  
  # File Operations
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  
  # MQTT Communication
  mqtt_client: ^10.10.0
  
  # Environment Variables
  flutter_dotenv: ^5.2.1
  
  # HTTP Requests
  http: ^1.2.1
  
  # Shared Preferences
  shared_preferences: ^2.3.2
  
  # Device Info
  device_info_plus: ^10.1.2
  
  # Cryptography
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env